# Generated by Django 5.2.16 on 2026-07-21 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('index', models.PositiveSmallIntegerField(help_text='Display order, e.g. 01, 02')),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(help_text='e.g. Match Ball, Pro Ball', max_length=255)),
                ('category', models.CharField(choices=[('match', 'Match'), ('training', 'Training'), ('academy', 'Academy'), ('street', 'Street')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('layering', models.CharField(blank=True, help_text='e.g. 5-Layer Premium Shell', max_length=255)),
                ('core', models.CharField(blank=True, help_text='e.g. Composite Bladder', max_length=255)),
                ('aero_tech', models.CharField(blank=True, help_text='e.g. Micro-Texturing', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Boot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Carousel display order')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('flagship', 'Flagship Build'), ('prototype', 'Prototype'), ('academy', 'Academy'), ('pro_match', 'Pro Match'), ('heritage', 'Heritage'), ('testing', 'Testing Phase'), ('concept', 'Concept Drop'), ('limited', 'Limited Stock'), ('upcoming', 'Upcoming')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='Django session key, ties cart to a browser session', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('ball', 'Ball'), ('boot', 'Boot')], max_length=10)),
                ('product_id', models.PositiveIntegerField(help_text='PK of the Ball or Boot')),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.URLField(blank=True, max_length=1000)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='advanced.cart')),
            ],
            options={
                'unique_together': {('cart', 'product_type', 'product_id')},
            },
        ),
    ]
